using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Polly;
using Polly.Retry;

namespace eShopSupport.Backend.Data;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options) : base(options)
    {
    }

    public DbSet<Customer> Customers { get; set; }

    public DbSet<Ticket> Tickets { get; set; }

    public DbSet<Message> Messages { get; set; }

    public DbSet<ProductCategory> ProductCategories { get; set; }

    public DbSet<Product> Products { get; set; }

    public DbSet<AgentExecution> AgentExecutions { get; set; }

    public DbSet<AgentTrace> AgentTraces { get; set; }

    public DbSet<DraftResponse> DraftResponses { get; set; }

    public DbSet<TriageAnalysis> TriageAnalyses { get; set; }

    public DbSet<TriageSettings> TriageSettings { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.Entity<Ticket>().HasMany(t => t.Messages).WithOne().OnDelete(DeleteBehavior.Cascade);
        modelBuilder.Entity<Ticket>().HasOne(t => t.Product);

        // Configure AgentExecution relationships
        modelBuilder.Entity<AgentExecution>()
            .HasMany(e => e.Traces)
            .WithOne()
            .HasForeignKey(t => t.AgentExecutionId)
            .OnDelete(DeleteBehavior.Cascade);
    }

    public static async Task EnsureDbCreatedAsync(IServiceProvider services, string? initialImportDataDir)
    {
        using var scope = services.CreateScope();
        using var dbContext = scope.ServiceProvider.GetRequiredService<AppDbContext>();

        // Wait until the DB is ready
        var pipeline = new ResiliencePipelineBuilder().AddRetry(new RetryStrategyOptions { Delay = TimeSpan.FromSeconds(3) }).Build();
        var createdDb = await pipeline.ExecuteAsync(async (CancellationToken ct) =>
            await dbContext.Database.EnsureCreatedAsync(ct));

        // Ensure TriageSettings table exists (for existing databases that were created before this feature)
        await EnsureTriageSettingsTableExists(dbContext);

        if (createdDb && !string.IsNullOrEmpty(initialImportDataDir))
        {
            await ImportInitialData(dbContext, initialImportDataDir);
        }
    }

    private static async Task EnsureTriageSettingsTableExists(AppDbContext dbContext)
    {
        try
        {
            // Check if the table exists by trying to query it
            await dbContext.TriageSettings.AnyAsync();

            // Table exists, check for and add missing columns (for existing databases)
            await dbContext.Database.ExecuteSqlRawAsync(@"
                ALTER TABLE ""TriageSettings""
                ADD COLUMN IF NOT EXISTS ""CurrentStatus"" VARCHAR(50) NOT NULL DEFAULT 'Idle',
                ADD COLUMN IF NOT EXISTS ""LastRunTime"" TIMESTAMP WITHOUT TIME ZONE,
                ADD COLUMN IF NOT EXISTS ""TicketsProcessedLastRun"" INTEGER NOT NULL DEFAULT 0,
                ADD COLUMN IF NOT EXISTS ""TotalTicketsProcessed"" INTEGER NOT NULL DEFAULT 0,
                ADD COLUMN IF NOT EXISTS ""CurrentActivity"" TEXT,
                ADD COLUMN IF NOT EXISTS ""CurrentActivityStarted"" TIMESTAMP WITHOUT TIME ZONE;
            ");
        }
        catch
        {
            // Table doesn't exist, create it with all columns
            await dbContext.Database.ExecuteSqlRawAsync(@"
                CREATE TABLE IF NOT EXISTS ""TriageSettings"" (
                    ""Id"" SERIAL PRIMARY KEY,
                    ""AutomaticTriageEnabled"" BOOLEAN NOT NULL,
                    ""LastModified"" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
                    ""CurrentStatus"" VARCHAR(50) NOT NULL DEFAULT 'Idle',
                    ""LastRunTime"" TIMESTAMP WITHOUT TIME ZONE,
                    ""TicketsProcessedLastRun"" INTEGER NOT NULL DEFAULT 0,
                    ""TotalTicketsProcessed"" INTEGER NOT NULL DEFAULT 0,
                    ""CurrentActivity"" TEXT,
                    ""CurrentActivityStarted"" TIMESTAMP WITHOUT TIME ZONE
                );
            ");
        }
    }

    private static async Task ImportInitialData(AppDbContext dbContext, string dirPath)
    {
        try
        {
            var customers = JsonSerializer.Deserialize<Customer[]>(
                File.ReadAllText(Path.Combine(dirPath, "customers.json")))!;

            var categories = JsonSerializer.Deserialize<ProductCategory[]>(
                File.ReadAllText(Path.Combine(dirPath, "categories.json")))!;

            var products = JsonSerializer.Deserialize<Product[]>(
                File.ReadAllText(Path.Combine(dirPath, "products.json")))!;

            var tickets = JsonSerializer.Deserialize<Ticket[]>(
                File.ReadAllText(Path.Combine(dirPath, "tickets.json")))!;

            // Explicitly remove the IDs so they will be auto-generated by the DB
            foreach (var ticket in tickets)
            {
                ticket.TicketId = 0;
                ticket.Customer = customers.First(c => c.CustomerId == ticket.CustomerId);
                ticket.CreatedAt = DateTime.UtcNow;
                foreach (var message in ticket.Messages)
                {
                    message.MessageId = 0;
                    message.CreatedAt = DateTime.UtcNow;
                }
            }
            foreach (var customer in customers)
            {
                customer.CustomerId = 0;
            }

            // These users correspond to entries in IdentityServer's TestUsers class
            await dbContext.Customers.AddAsync(new Customer { CustomerId = 10000, FullName = "Alice Smith" });
            await dbContext.Customers.AddAsync(new Customer { CustomerId = 10001, FullName = "Bob Smith" });

            await dbContext.Customers.AddRangeAsync(customers);
            await dbContext.ProductCategories.AddRangeAsync(categories);
            await dbContext.Products.AddRangeAsync(products);
            await dbContext.Tickets.AddRangeAsync(tickets);
            await dbContext.SaveChangesAsync();
        }
        catch
        {
            // If the initial import failed, we drop the DB so it will try again next time
            await dbContext.Database.EnsureDeletedAsync();
            throw;
        }
    }
}
